"""
Generated by Google agy:
NOT part of the final project
calculate_final_score.py

Calculates 'final_score' for a QSO result dictionary (as initialized by _init_result in share.py).
Formula: final_score = (3 * cw_qsos) + (2 * ph_qsos)
"""

from typing import Dict, Any


def calculate_final_score(result: Dict[str, Any]) -> Dict[str, Any]:
    """
    Calculates final_score by adding 3 times cw_qsos and 2 times ph_qsos,
    and stores it into result['final_score'].

    Args:
        result: A dictionary matching the structure returned by _init_result().

    Returns:
        The updated result dictionary.
    """
    cw_count = result.get('cw_qsos', 0)
    ph_count = result.get('ph_qsos', 0)

    result['final_score'] = (3 * cw_count) + (2 * ph_count)
    return result


def create_sample_result(callsign: str = "W5XYZ", cw_qsos: int = 0, ph_qsos: int = 0) -> Dict[str, Any]:
    """
    Creates a result dictionary using the structure from _init_result in share.py.
    """
    return {
        'callsign': callsign,
        'cab': None,
        'header_attribs': {},
        'qso_data': [],
        'year': 2026,
        'exchange': '',
        'category': 'NON-LA',
        'dxcc_code': 0,
        'dxcc_entity': '',
        'final_score': 0,
        'cw_qsos': cw_qsos,
        'ph_qsos': ph_qsos,
        'dg_qsos': 0,
        'ry_qsos': 0,
        'qso_points': 0,
        'total_qsos': cw_qsos + ph_qsos,
        'valid_qsos': cw_qsos + ph_qsos,
        'total_multipliers': 0,
        'counties_worked': set(),
        'counties_worked_multiplier': 0,
        'states_worked': set(),
        'states_worked_multiplier': 0,
        'provinces_worked': set(),
        'provinces_worked_multiplier': 0,
        'dx_worked': set(),
        'dx_worked_multiplier': 0,
        'counties_activated': set(),
        'de_exch_rcvd': set(),
        'dx_exch_sent': set(),
        'score_wo_bonus': 0,
        'rover_bonus_points': 0,
        'county_bonus_points': 0,
        'worked_special_station': False,
        'num_n5lcc_contacts': 0,
        'qsos_by_band': {'160': 0, '80': 0, '40': 0, '20': 0, '15': 0, '10': 0, '6': 0, '2': 0},
        'qsos_by_mode': {'PH': ph_qsos, 'CW': cw_qsos, 'RY': 0, 'DG': 0},
        'qsos_by_hour': [0] * 24,
        'bands_worked': set(),
        'uniques': 0,
        'nils': 0,
        'busteds': 0,
        'dup_qsos': 0,
        'errors': [],
        'warnings': [],
        'is_valid': True
    }


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description="Calculate final_score based on cw_qsos and ph_qsos.")
    parser.add_argument("--cw", type=int, default=39, help="Number of CW QSOs (default: 39)")
    parser.add_argument("--ph", type=int, default=12, help="Number of Phone QSOs (default: 12)")
    parser.add_argument("--callsign", type=str, default="AA0AW", help="Station callsign (default: AA0AW)")
    args = parser.parse_args()

    # Initialize result dictionary (matching _init_result format from share.py)
    result = create_sample_result(callsign=args.callsign, cw_qsos=args.cw, ph_qsos=args.ph)

    print(f"Initial state for {result['callsign']}:")
    print(f"  cw_qsos: {result['cw_qsos']}")
    print(f"  ph_qsos: {result['ph_qsos']}")
    print(f"  final_score: {result['final_score']}")

    # Calculate final score: 3 * cw_qsos + 2 * ph_qsos
    calculate_final_score(result)

    print("\nAfter calculation (3 * cw_qsos + 2 * ph_qsos):")
    print(f"  3 * {result['cw_qsos']} + 2 * {result['ph_qsos']} = {3 * result['cw_qsos']} + {2 * result['ph_qsos']} = {result['final_score']}")
    print(f"  result['final_score'] = {result['final_score']}")
